config/routes.rb
Webmanager::Engine.routes.draw do
  root to: 'home#index'
  devise_for :users, class_name: "Webmanager::User", :module => :devise
  devise_scope :user do
    get 'sign_in', to: '/devise/sessions#new'
    delete 'sign_out', to: '/devise/sessions#destroy'
  end
  resources :articles
  resources :blog_assets
  resources :forms
  resources :form_fields
  resources :form_responses
  resources :notes
  resources :tags
  resources :newsletter_receivers
  resources :events do
    collection do
      post :notify
    end
  end
end

app/models/webmanager/application_record.rb
module Webmanager
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/webmanager/article.rb
module Webmanager
  class Article < ApplicationRecord

    validates_presence_of :title, :author_id, :permalink, :body
    belongs_to :user, :foreign_key => 'author_id'
    has_many :taggings, dependent: :destroy
    has_many :tags, through: :taggings
    has_many :assets, dependent: :destroy
    has_many :blog_assets, through: :assets


    def self.tagged_with(name)
      Tag.find_by_name!(name).articles
    end

    def tag_list
      tags.map { |t| t.name }
    end

    def tag_list=(names)
      self.tags = names.split(",").map do |n|
        Tag.where(name: n.strip).first_or_create!
      end
    end

    def asset_list
      blog_assets.map{ |t| t.id}.join(',')
    end

    def asset_list=(ids)
      self.blog_assets= ids.split(",").map do |n|
        BlogAsset.where(id:n).first!
      end
    end

  end
end

app/models/webmanager/asset.rb
module Webmanager
  class Asset < ApplicationRecord
    belongs_to :blog_asset
    belongs_to :article
  end
end

app/models/webmanager/blog_asset.rb
module Webmanager
  class BlogAsset < ApplicationRecord
    has_many :assets, dependent: :destroy
    has_many :articles, through: :assets
    has_attached_file :asset, styles: Webmanager.image_styles
    validates_attachment_content_type :asset,
                                      :content_type => %w(image/jpeg image/jpg image/png image/gif application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document),
                                      :message => 'only (png/gif/jpeg) images'

    before_post_process :skip_for_files
    before_save :extract_dimensions
    serialize :dimensions

    def skip_for_files
      ! %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document).include?(asset_content_type)
    end
    def image?
      asset_content_type =~ %r{^(image|(x-)?application)/(bmp|gif|jpeg|jpg|pjpeg|png|x-png)$}
    end

    private
    def extract_dimensions
      return unless image?
      tempfile = asset.queued_for_write[:original]
      unless tempfile.nil?
        geometry = Paperclip::Geometry.from_file(tempfile)
        self.dimensions = [geometry.width.to_i, geometry.height.to_i]
      end
    end
  end
end

app/models/webmanager/event.rb
module Webmanager
  class Event < ApplicationRecord
    validates_presence_of :name, :location
  end
end

app/models/webmanager/form.rb
module Webmanager
  class Form < ApplicationRecord

    has_many :form_fields, :class_name => 'Webmanager::FormField', dependent: :destroy
    has_many :form_responses
    accepts_nested_attributes_for :form_fields, :reject_if => lambda { |a| a[:name].blank? }, :allow_destroy => true
    accepts_nested_attributes_for :form_responses

    validates_presence_of :name
  end
end

app/models/webmanager/form_field.rb
module Webmanager
  class FormField < ApplicationRecord
    belongs_to :forms, :class_name => 'Webmanager::Form', optional: true
  end
end

app/models/webmanager/form_response.rb
module Webmanager
  class FormResponse < ApplicationRecord
    belongs_to :form
    serialize :response, Hash
    before_save :serialize_response

    def serialize_response
      serializable_hash(only: :response)
      # abort(serializable_hash(only: :response).inspect)
    end
  end
end

app/models/webmanager/newsletter_receiver.rb
module Webmanager
  class NewsletterReceiver < ApplicationRecord
    validates_presence_of :email
    validates_uniqueness_of :email, message: 'You have already subscribed!'
  end
end

app/models/webmanager/note.rb
module Webmanager
  class Note < ApplicationRecord
    belongs_to :webmanager_user, :class_name => 'Webmanager::User', :foreign_key => 'author_id'

    validates_presence_of :title, :body
  end
end

app/models/webmanager/tag.rb
module Webmanager
  class Tag < ApplicationRecord
    has_many :taggings, dependent: :destroy
    has_many :articles, through: :taggings
  end
end

app/models/webmanager/tagging.rb
module Webmanager
  class Tagging < ApplicationRecord
    belongs_to :tag
    belongs_to :article
  end
end

app/models/webmanager/user.rb
module Webmanager
  class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable, :timeoutable

    has_many :notes, :class_name => 'Webmanager::Note', :foreign_key => 'author_id'
    has_many :articles, :foreign_key => 'author_id'



    def name
      first_name + ' ' + last_name
    end

  end
end

app/controllers/webmanager/application_controller.rb
module Webmanager
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?


    def after_sign_in_path_for(resource)
      '/webmanager'
    end

    protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end
  end
end

app/controllers/webmanager/articles_controller.rb
 require_dependency "webmanager/application_controller"

module Webmanager
  class ArticlesController < ApplicationController
    before_action :authenticate_user!, except: :show

    def index
      @articles = params[:q] ? Article.where(title: params[:q]) : Article.all
    end

    def show
      @article = Article.find(params[:id])
      respond_to do |format|
        format.html { render :show, location: @article }
        format.json { render json: @article }
      end
    end

    def new
      @article = current_user.articles.new
    end

    def create
      @article = current_user.articles.new(article_params)
      @article.permalink = @article.title.downcase.gsub(' ', '-')
      @article.tag_list = params["article"]["tag_list"].reject { |c| c.empty? }.join(',')
      @article.asset_list = params["article"]["asset_list"].reject { |c| c.empty? }.join(',')
      respond_to do |format|
        if @article.save
          format.html { redirect_to @article, notice: 'Article was successfully created!' }
          format.json { render :show, status: :created, location: @article }
        else
          format.html { render :new }
          format.json { render json: @article.errors, status: :unprocessable_entity }
        end
      end
    end

    def edit
      @article = Article.find(params[:id])
      @tags = Webmanager::Tag.all

    end

    def update
      @article = Article.find(params[:id])
      @article.permalink = params["article"]["title"].downcase.gsub(' ', '-')
      @article.tag_list = params["article"]["tag_list"].reject { |c| c.empty? }.join(',')
      @article.asset_list = params["article"]["asset_list"].reject { |c| c.empty? }.join(',')
      respond_to do |format|
        if @article.update(article_params)
          format.html { redirect_to @article, notice: 'Article was successfully updated!' }
          format.json { render :show, status: :created, location: @article }
        else
          format.html { render :edit }
          format.json { render json: @article.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @article = Article.find(params[:id])
      @article.destroy
      respond_to do |format|
        format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
    def article_params
      params.require(:article).permit(:id, :title, :description, :body, :permalink, :author_id, :tag_list, :asset_list)
    end
  end
end

app/controllers/webmanager/blog_assets_controller.rb
require_dependency "webmanager/application_controller"

module Webmanager
  class BlogAssetsController < ApplicationController
    before_action :authenticate_user!, except: :show
    def index
      @assets = BlogAsset.all
      @new_asset = BlogAsset.new
    end

    def create
      # abort(params.inspect)
      @asset = BlogAsset.new(asset_params)
      if @asset.save
        redirect_back(fallback_location: root_path)
      end
    end

    def destroy
      @asset = BlogAsset.find(params[:id])
      @asset.destroy
      respond_to do |format|
        format.html { redirect_back(fallback_location: root_path, notice: 'Asset was successfully destroyed.') }
        format.json { head :no_content }
      end
    end

    private
    def asset_params
      params.require(:blog_asset).permit(:id, :asset, :dimensions)
    end
  end
end

app/controllers/webmanager/events_controller.rb
require_dependency "webmanager/application_controller"

module Webmanager
  class EventsController < ApplicationController
    before_action :authenticate_user!, except: :show
    before_action :set_event, only: [:show, :edit, :update, :destroy]

    # GET /events
    def index
      @events = Event.all
      @date = params[:date] ? Date.parse(params[:date]) : Date.today
      @events_by_date = @events.group_by(&:start_date)
    end

    # GET /events/1
    def show
    end

    # GET /events/new
    def new
      @event = Event.new
    end

    # GET /events/1/edit
    def edit
    end

    # POST /events
    def create
      @event = Event.new(event_params)
      if @event.save
        redirect_to @event, notice: 'Event was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /events/1
    def update
      if @event.update(event_params)
        redirect_to @event, notice: 'Event was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /events/1
    def destroy
      @event.destroy
      redirect_to events_url, notice: 'Event was successfully destroyed.'
    end

    def notify
      NewsletterReceiver.all.each do |s|
        EventsMailer.attend_event(s.email, params[:event]).deliver
      end
      redirect_back(fallback_location: root_path, notice: 'Everyone notified successfully!')
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def event_params
      params.require(:event).permit(:name, :description, :start_date, :end_date, :location, :organizer)
    end
  end
end

app/controllers/webmanager/form_fields_controller.rb
require_dependency "webmanager/application_controller"

module Webmanager
  class FormFieldsController < ApplicationController
    before_action :authenticate_user!, except: :show

    def new
      @form_field = FormField.new
    end
    def create
      @form_field = FormField.new(form_field_params)
      @form_field.name = @form_field.name.downcase.gsub(' ','_')
      @form_field.save!
    end
    def edit
      @form_field = FormField.find(params[:id])
    end
    def update
      @form_field = FormField.find(params[:id])
      @form_field.update(form_field_params)
    end
    def destroy
      @form_field = FormField.find(params[:id])
      @form_field.destroy!
    end
    private
    def form_field_params
      params.require(:form_field).permit(:webmanager_form_id, :name, :label, :hint, :placeholder, :as, :collection, :disabled, :required)
    end
  end
end

app/controllers/webmanager/form_responses_controller.rb
require_dependency "webmanager/application_controller"

module Webmanager
  class FormResponsesController < ApplicationController
    skip_before_action :verify_authenticity_token

    def index
      @responses = FormResponse.all
    end

    def create
      id = params["form_response"]["form_id"].to_i
      @form = Form.find_by(id: id)
      @form_response = @form.form_responses.new(form_response_params)
      @form_response.response = params["form_response"]["response"].to_unsafe_h
      if @form_response.save!
        FormResponseMailer.query_received(@form_response).deliver
        redirect_back(fallback_location: root_path,notice: @form.success_message)
      end
    end

    def show
      @response = FormResponse.find(params[:id])
    end

    private
    def form_response_params
      params.require(:form_response).permit(:form_id, :response)
    end
  end
end

app/controllers/webmanager/forms_controller.rb
require_dependency "webmanager/application_controller"

module Webmanager
  class FormsController < ApplicationController

    def index
      @forms = Form.all
    end

    def show
      @form = Form.find(params[:id])
    end

    def new
      @form = Form.new
      @form.form_fields.build
    end

    def create
      @form = Form.new(form_params)
      @form.form_fields.name.downcase.gsub(' ','_')
      respond_to do |format|
        if @form.save
          format.html { redirect_to @form, notice: 'Form was successfully created!' }
          format.json { render :show, status: :created, location: form }
        else
          format.html { render :new }
          format.json { render json: form.errors, status: :unprocessable_entity }
        end
      end
    end

    def edit
      @form = Form.find(params[:id])
    end

    def update
      @form = Form.find(params[:id])
      respond_to do |format|
        if @form.update(form_params)
          format.html { redirect_to @form, notice: 'Form was successfully updated!' }
          format.json { render :show, status: :created, location: form }
        else
          format.html { render :edit }
          format.json { render json: form.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @form = Form.find(params[:id])
      if @form.destroy
        redirect_to forms_path, notice: 'Form deleted successfully!'
      end
    end

    private
    def form_params
      params.require(:form).permit(:id, :name, :description, :success_message, :primary_mail, form_fields_attributes: [:id, :form_id, :name, :label, :hint, :placeholder, :as, :collection, :disabled, :required, :_destroy],
                                   form_responses: [:form_id, :response])
    end
  end
end

app/views/webmanager/articles/_form.html.erb
<div class="mdl-card__supporting-text">
<%= form_for(article) do |f| %>
  <% if article.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

          <ul>
            <% article.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
  <% end %>
  <div class="mdl-textfield mdl-js-textfield mdl-cell mdl-cell--12-col">
    <%= f.text_field :title, class:'mdl-textfield__input' %>
    <%= f.label :title, class:'mdl-textfield__label'%>
  </div>
  <div class="mdl-textfield mdl-js-textfield mdl-cell mdl-cell--12-col">
    <%= f.text_area :description, class:'mdl-textfield__input', rows: 3%>
    <%= f.label :description, class:'mdl-textfield__label'%>
  </div>
  <div class="hidden" id="assets_show">
  <div class="flex-checkboxes">
  <%= hidden_field_tag "article[asset_list][]", nil %>
      <% Webmanager::BlogAsset.all.each do |asset| %>
            <%= check_box_tag "article[asset_list][]", asset.id, article.asset_list.include?(asset.id.to_s), id: dom_id(asset) %>
            <%= label_tag dom_id(asset), (image_tag asset.asset.url(:thumb)), onClick: "selected('#{dom_id(asset)}')", "data-asset":dom_id(asset), class: article.asset_list.include?(asset.id.to_s) ? 'selected' : ''%>
      <% end %>
  </div>
  </div>
  <div class="mdl-grid">
  <div class="mdl-cell mdl-cell--2-col">
  <a id="select-asset" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent">
      Select Assets
    </a>
  </div>
  <div class="mdl-cell mdl-cell--col-10">
      <%=f.select :tag_list, options_for_select(Webmanager::Tag.all.map{|t| [t.name, t.name]}, :selected => article.tag_list), {}, {:class => 'tag-list',:multiple => true}%>
  </div>
  </div>
  <div class="mdl-cell mdl-cell--12-col">
    <%= f.trix_editor :body%>
  </div>
  </div>
  <div class="mdl-card__actions mdl-card--border">
  <% if @article.persisted? %>
    <%= f.submit "Update Article", class:'mdl-button mdl-js-button mdl-button--raised mdl-button--accent' %>
    <%= link_to 'Cancel', article_path(article), class:'mdl-button mdl-js-button' %>
  <% else %>
    <%= f.submit "Create Article", class:'mdl-button mdl-js-button mdl-button--raised mdl-button--accent' %>
    <%= link_to 'Cancel', articles_path, class:'mdl-button mdl-js-button' %>
  <% end %>
  </div>
<% end %>

app/views/webmanager/articles/edit.html.erb
<div class="mdl-card mdl-shadow--2dp mdl-cell mdl-cell--10-col-desktop mdl-cell--1-offset-desktop mdl-cell--12-col">
  <%= render 'form', article: @article %>
</div>

app/views/webmanager/articles/index.html.erb
<%= render :partial => 'webmanager/shared/title_row' %>
<div class="mdl-cell mdl-cell--12-col">
  <table class="mdl-data-table mdl-shadow--2dp mdl-cell mdl-cell--12-col">
    <thead>
    <tr>
      <th>Name</th>
      <th>Author</th>
      <th>Created At</th>
      <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    <% if @articles.empty? %>
        <%= render :partial => 'webmanager/shared/empty' %>
    <% else %>
        <% @articles.each do |article| %>
            <tr>
              <td class="mdl-typography--text-left-custom"><%= article.title %></td>
              <td class="mdl-typography--text-center-custom"><%= article.user.name %></td>
              <td class="mdl-typography--text-center-custom "><%= article.created_at.to_formatted_s(:long) %></td>
              <td class="mdl-typography--text-center-custom"><%= link_to '<i class="material-icons">open_in_new</i>'.html_safe, article, class: 'mdl-button mdl-js-button mdl-button--fab mdl-button--mini-fab mdl-button--colored' %>
                <%= link_to '<i class="material-icons">edit_pencil</i>'.html_safe, edit_article_path(article), class: 'mdl-button mdl-js-button mdl-button--fab mdl-button--mini-fab mdl-button--colored' %></td>
            </tr>
        <% end %>
    <% end %>
    </tbody>
  </table>
</div>

app/views/webmanager/articles/new.html.erb
<div class="mdl-card mdl-shadow--2dp mdl-cell mdl-cell--10-col-desktop mdl-cell--1-offset-desktop mdl-cell--12-col">
    <%= render 'form', article: @article %>
</div>

app/views/webmanager/articles/show.html.erb
<div class="mdl-card mdl-shadow--2dp mdl-cell mdl-cell--10-col-desktop mdl-cell--1-offset-desktop mdl-cell--12-col">
  <div class="mdl-card__published-date">
    <h6>Created by <%= @article.user.name %> at <%= @article.created_at.to_formatted_s(:long) %></h6>
  </div>
  <div class="mdl-card__title">
    <h2 class="mdl-card__title-text"><%= @article.title %></h2>
  </div>
  <div class="mdl-card__supporting-text">
    <%= raw @article.body %>
    <div>
      <% @article.blog_assets.each do |asset| %>
          <%= image_tag asset.asset.url(:thumb) %>
      <% end %>
    </div>
    <% @article.tag_list.each do |t| %>
        <span class="mdl-chip">
          <span class="mdl-chip__text"><%= t %></span>
        </span>
    <% end %>
  </div>
  <div class="mdl-card__actions mdl-card--border">
    <%= link_to 'Edit Article', edit_article_path(@article), class: 'mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect' %>
    <%= link_to 'Delete Article', article_path(@article), class: 'mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect', method: :delete, data: {confirm: "Are you sure?"} %>
  </div>
</div>